# Generated by Django 4.2.1 on 2023-08-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='members', to='roles.role'),
        ),
    ]
