# Generated by Django 4.2.1 on 2023-08-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('api', '0002_appuser_coins_appuser_xp_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='roles',
            field=models.ManyToManyField(related_name='members', to='roles.role'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
