# Generated by Django 4.2.1 on 2023-08-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appuser_roles_alter_appuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='course_manager',
            field=models.BooleanField(default=False),
        ),
    ]
