# Generated by Django 4.2.1 on 2023-07-25 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(to='api.AppUser', on_delete=models.SET_NULL, null=True, related_name='courses')),
                ('contributors', models.ManyToManyField(to='api.AppUser', related_name='contributed_courses', blank=True)),
                ('rating', models.SmallIntegerField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField()),
                ('update_count', models.IntegerField(default=0)),
            ],
        ),
    ]
