# Generated by Django 4.2.1 on 2023-09-02 13:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=3000, validators=[django.core.validators.MinLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
