# Generated by Django 4.2.1 on 2023-07-29 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_alter_course_contributors_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
