# Generated by Django 4.2.1 on 2023-09-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_duration_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='available_for_any_subscriber',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='available_for_buyers_only',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='available_for_everyone',
            field=models.BooleanField(),
        ),
    ]
