# Generated by Django 4.2.1 on 2023-09-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_available_for_any_subscriber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='available_for_any_subscriber',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='available_for_buyers_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='available_for_everyone',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
