# Generated by Django 4.2.1 on 2023-09-02 15:38

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_available_for_any_subscriber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=3000, validators=[django.core.validators.MinLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to=courses.models.upload_to),
        ),
        migrations.AlterField(
            model_name='course',
            name='mode',
            field=models.SmallIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
