# Generated by Django 4.2.1 on 2023-07-31 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_warning_course_related_courses_section_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='warning',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='courses.course'),
        ),
    ]
