# Generated by Django 4.2.1 on 2023-08-16 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0011_alter_course_author_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='available_for_any_subscriber',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='available_for_buyers_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='available_for_everyone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='subscribers',
            field=models.ManyToManyField(related_name='courses_that_user_bought', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('courses', models.ManyToManyField(related_name='categories', to='courses.course')),
                ('qualified_users', models.ManyToManyField(related_name='qualified_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
