# Generated by Django 4.2.1 on 2023-08-18 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0012_course_available_for_any_subscriber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='courses_that_user_bought', to=settings.AUTH_USER_MODEL),
        ),
    ]
