# Generated by Django 4.2.1 on 2023-08-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.RemoveField(
            model_name='role',
            name='course_manager',
        ),
    ]
